### ISSUE TITLE
pypi release outdated

### ISSUE THREAD

**Issue by LeoLTM** [JarbasHiveMind/HiveMind-cli#10]
Everytime I try to install the HiveMind-cli on my Pi 0 W, this happens:

`Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/jarbas-utils/`

EDIT:
I replaced all the "jarbas-utils" lines with "ovos-utils", but now I get:

```Traceback (most recent call last):
  File "/usr/local/bin/HiveMind-cli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/cli_satellite/__main__.py", line 59, in main
    args.name, args.access_key, args.crypto_key)
  File "/usr/local/lib/python3.7/dist-packages/cli_satellite/__main__.py", line 18, in connect_to_hivemind
    useragent=useragent)
  File "/usr/local/lib/python3.7/dist-packages/cli_satellite/__init__.py", line 24, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got multiple values for argument 'crypto_key'```

**Comment by ChanceNCounter** [comment]
What versions are you getting of the various HiveMind packages? I can't find any remaining references to jarbas-utils. This repo's only dep is HiveMind itself, which was migrated to OVOS-utils in December.

**Comment by ChanceNCounter** [comment]
Nevermind, I see the problem. We're way outdated on pypi. Thank you kindly for the report!
