### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by markus-schott** [JarbasHiveMind/HiveMind-cli#15]
When i am trying to install via the provided pip command everything seems fine, but when i execute 
`HiveMind-cli --help`

i get this error. Am i missing something?

`Traceback (most recent call last):
  File "/home/mschotte/.local/bin/HiveMind-cli", line 5, in <module>
    from cli_satellite.__main__ import main
  File "/home/mschotte/.local/lib/python3.8/site-packages/cli_satellite/__init__.py", line 2, in <module>
    from jarbas_utils.log import LOG
ModuleNotFoundError: No module named 'jarbas_utils'`

**Comment by qnlbnsl** [comment]
also, if you build from the source the `--name` argument is missing which then crashes the cli as well.

**Comment by qnlbnsl** [comment]
> also, if you build from the source the `--name` argument is missing which then crashes the cli as well.

nvm i was being stoooopid. i used ws:\\ instead of ws:// 
Also, need to ensure that the hivemind dire under you XDG CONFIG (likely ~/.config) is present or else it will give you an error about not being able to find a .asc file

**Comment by neatbasis** [comment]
Had the same problem. As a workaround you can ```pip install git+https://github.com/JarbasHiveMind/HiveMind-cli.git@V0.5.0a2``` to get the latest release as of now, which is not currently available in PyPI

This will give you hivemind-cli (in lowercase letters, the current README is not up to date either)
